### ISSUE TITLE
Nuki trigger in scenes

### ISSUE THREAD

**Issue by Razeeer** [lukasroegner/homebridge-nuki#24]
Hello and many thanks for the great plugin!

I have a problem and that is when I insert the nuki lock into a scene example with the function unlock and execute the scene when the lock is already open it is still triggered.

The lock makes an attempt to unlock and then stops again because it has already been at the end position. This does not sound healthy.

Do you have the possibility to add a function that your plugin only closes or opens when the lock does not have the target position?

**Comment by lukasroegner** [comment]
@Razeeer I agree, the plugin should check it (as the Nuki Bridge obviously doesn't). I don't use lock s in scenes, that's why I haven't noticed yet.

**Comment by Razeeer** [comment]
Sorry for the late answer, I was on vacation.-)

Would be really great if you would implement it soon. Thanks a lot!

**Comment by lukasroegner** [comment]
There are two separate issues that we should take a look at:

**Lock if already locked:**
For this scenario, I added a new property `lockFromLockedToLocked` to the device configuration. Now, by default, the lock does not lock if it is already locked (value  `false`). If the value is set to `true`, the lock executes the lock action again even if it is already locked. This is a valid move, as you could want to lock it twice (360 degree the first time and 720 degree the second time).
You can find this update on the **development** branch.

**Unlock if already unlocked:**
This scenario is a bit tricky. If you unlock the HomeKit accessory, there are two possible actions:
* If the door is locked, it will either unlock or unlock+unlatch, depending on the configuration value for `unlatchFromLockedToUnlocked`.
* If the door is already unlocked, it will unlatch only if you've set the configuration value for `unlatchFromUnlockedToUnlocked`.

I could not reproduce the behavior you described (double unlock) with my door, which is why I assume that your door does not support unlatching? Could you tell me your configuration values and the type of door (knob, no knob, unlatch possible)?

**Comment by Razeeer** [comment]
I own two Nukis, one at the front door is unlocked and unlatch in use. With the second one at the basement door I can only use unlock there is no unlatch function.

Here is my Config that I use

"platforms": [
{
"platform": "NukiPlatform",
"hostNameOrIpAddress": "",
"hostCallbackApiPort": ,
"bridgeIpAddress": "",
"bridgeApiPort": ,
"bridgeApiToken": "",
"devices": [
{
"nukiId": ,
"unlatchLock": true
"unlatchFromLockedToUnlocked": false,
"unlatchFromUnlockedToUnlocked": true,
"unlatchLockPreventUnlatchIfLocked": false,
},
{
"nukiId":,
"unlatchLock": false
"unlatchFromLockedToUnlocked": false,
"unlatchFromUnlockedToUnlocked": true,
}
]
}
]
}

**Comment by lukasroegner** [comment]
> I have a problem and that is when I insert the nuki lock into a scene example with the function unlock and execute the scene when the lock is already open it is still triggered.
> 
> The lock makes an attempt to unlock and then stops again because it has already been at the end position. This does not sound healthy.

On which of the two Nukis does this issue appear?

**Comment by Razeeer** [comment]
The second one in the config, this one is without unlatch in the basement.

**Comment by lukasroegner** [comment]
Then you should set the `unlatchFromUnlockedToUnlocked` to `false`. This causes your issue.

**Comment by Razeeer** [comment]
I'd have to test it again. Let you know in the morning since I'm on the road until tomorrow.
Thanks for the help 👍

**Comment by Razeeer** [comment]
Good morning, I just tested it and disabled unlatchFromUnlockedToUnlocked. This solved the problem.

So it was a user error. Sorry about that.

Thank you for your support.
