### ISSUE TITLE
Status problems

### ISSUE THREAD

**Issue by derthobo** [lukasroegner/homebridge-nuki#39]
Hello :)

With the plug-in I can control my smart lock and the opener. After updating the Homebridge to v 1.1.1 the behavior after unlock the latch or the opener has changed. The status doesn’t fall back to closed. I’m using the actual release of the homebridge-nuki-plug-in. I’ve posted a screenshot of the Home-app, where you can see the latch (Flur Schnapper) after I closed it manually.

Edit: The locking-process is infinite... after restarting the Homebridge the status is back to closed. Till the next opening-process.

![image](https://user-images.githubusercontent.com/56515540/86472882-2d130800-bd40-11ea-98c6-5cb0e748d9ae.jpeg)

**Comment by felixmueller** [comment]
Hi @derthobo,
I just double checked but I cannot confirm this in my case. I also have Homebridge 1.1.1. installed and I own an Opener and a Smart Lock.
Both, the Opener Lock and the Door Latch Lock are automatically reset after opening.
Maybe there is an issue with your Bridge callbacks?
Cheers,
Felix

**Comment by derthobo** [comment]
I’ve (my brother) solved the issue. It was because I’ve changed the instance and it was an old callback Server registered on the bridge. Here is the solution:
[](https://www.qdxingtu.com/key/unlatchLock%20Status.html)

**Comment by DrawringSimon** [comment]
> Hi @derthobo,
> I just double checked but I cannot confirm this in my case. I also have Homebridge 1.1.1. installed and I own an Opener and a Smart Lock.
> Both, the Opener Lock and the Door Latch Lock are automatically reset after opening.
> Maybe there is an issue with your Bridge callbacks?
> Cheers,
> Felix

Hi @felixmueller,
I am trying to isolate where my problem with the Opener is so that I can make necessary adjustments, but I want to be clear on how it is supposed to work. I've been working on this for only a couple of days since I just received my Nuki Opener. My Opener unlocks the gate, however, it stays in the "Unlocking" status until I manually press the homekit accessory button again. Then it goes back to "Locked" status. It sounds like yours automatically returns to Locked status after a short time? This is how I expect it should work as this was the case with @lukasroegner 's Nello plugin that I used.

I have cleared old callback servers and my log does not show callback errors:
[7/10/2020, 9:05:46 AM] [NukiPlatform] Callback server started.
[7/10/2020, 9:05:46 AM] [NukiPlatform] API started.
[7/10/2020, 9:05:53 AM] [NukiPlatform] Callback registered.

Do you get a log message saying that the Nuki is locked again? I only get the Unlock log entry each time, no lock entry and no errors. 
[7/10/2020, 9:29:47 AM] [NukiPlatform] XXXXXXXXX - Unlock
