### ISSUE TITLE
Question on accessory services grouping

### ISSUE THREAD

**Issue by felixmueller** [lukasroegner/homebridge-nuki#5]
Hi Lukas,

I am still waiting for iOS 13.1 before I upgrade my iPhone, but I have a question on the grouping of accessory services: In your current implementation, each lock is exposed as accessory and the optional RTO and Continuous Mode services are exposed in a second accessory named "[Lock] Settings".
Is it possible to add these two services to the lock accessory itself instead of an own switch accessory? Or is it impossible to group services of different kinds? It would be easier to operate these features via control center, because the space for the favorites is limited to 9 items.

Thanks for your good work and any clarification about this!

Cheers
Felix

**Comment by lukasroegner** [comment]
Hi Felix,

There are two main reasons why I decided to use two separate accessories:
* UI: using several services (lock, switch, another switch) in one accessory looks just ugly in the iOS interface (which you cannot influence)
* Settings: as soon as you have two "main" services in a single accessory, the advanced properties and settings (swipe down in the details view of an accessory) are not visible.

We had a discussion on how this can be solved in https://github.com/lukasroegner/homebridge-dyson-pure-cool/issues/6
Finally, I decided that using a separate accessory for "settings" switches is the way to go, as it saves you one icon in the Home app (instead of having two switches, they can be combined to one accessory), all settings of the "main" accessory are displayed properly and two switches side-by-side are a beautiful solution.
