### ISSUE TITLE
Lock Status Update

### ISSUE THREAD

**Issue by adnanshah87** [lukasroegner/homebridge-nuki#63]
Hi Lukas,

first of all thanks for the plugin - great work!
I currently experience an issue that the lock status is not updated when manually locking or unlocking the device.
Do you know what might be the reason for that?

Thanks
Adnan

**Comment by lukasroegner** [comment]
Hi @adnanshah87, please check whether the callback works correctly. Do you have a Nuki Opener? If so, do you get ring notifications? If not, you can checks the logs for updates via callback from Nuki Bridge:
- When starting homebridge, you should see the log entry `Callback registered`
- If you perform a lock action, you should see the log entry with `Updating Door State`

**Comment by adnanshah87** [comment]
Hi Lukas thank you for your answer I have received the info call back registered however when I do a lock action I do not get the info on updating door state do you know what could cause this issue?

**Comment by wapster182** [comment]
Exactly the same issue on my end! Would love a fix for this!

**Comment by wapster182** [comment]
I found the issue! It was my mistake!
What did I do wrong? Here is the answer: In the homebridge config, I used the localhost IP 127.0.0.1 for the hostNameOrIpAddress, because the plugin is installed on the raspi itself. BUT then the callback will fail, because this localhost IP will be added to the Nuki Bridge callback table. When it tries to send the callback, the routing obviously will not work, as sending it so itself will not come back to the raspi homebridge instance...
So after entering the IP of my raspi, everything works great!
